# Generated by Django 5.2.4 on 2025-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagodas', '0002_savedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoda',
            name='events',
            field=models.TextField(blank=True, verbose_name='Sự kiện/lễ lớn'),
        ),
        migrations.AddField(
            model_name='pagoda',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giờ mở cửa'),
        ),
        migrations.AddField(
            model_name='pagoda',
            name='sect',
            field=models.CharField(blank=True, max_length=50, verbose_name='Trường phái'),
        ),
        migrations.AddField(
            model_name='pagoda',
            name='target_audience',
            field=models.CharField(blank=True, max_length=50, verbose_name='Đối tượng phục vụ'),
        ),
        migrations.AddField(
            model_name='pagoda',
            name='transportation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phương tiện di chuyển'),
        ),
    ]
